export const projects = [
    {
        title: "Project 1",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: ["/images/Ask Freelancer/1.png", "/images/Ask Freelancer/2.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",]
    },
    {
        title: "Project 11",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet. Additionally, the project offers a method for enhancing the skills and expertise of users interested in learning, along with ensuring the seamless provision of software services.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: ["/images/Ask Freelancer/1.png", "/images/Ask Freelancer/2.png",
            "/images/Ask Freelancer/3.png", "/images/Ask Freelancer/4.png",
            "/images/Ask Freelancer/5.png", "/images/Ask Freelancer/6.png",
            "/images/Ask Freelancer/7.png", "/images/Ask Freelancer/8.png",
            "/images/Ask Freelancer/9.png", "/images/Ask Freelancer/10.png",
            "/images/Ask Freelancer/11.png", "/images/Ask Freelancer/12.png",
            "/images/Ask Freelancer/13.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",
            "Bootstrap (CSS framework)",
            "Firebase",
            "Sass",
            "Pusher realtime APIs",
            "Axios (Restful API)"],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",
            "Make a complaint", "Recharge your bank wallet", "Managing publications (requesting services)",
            "Approval and agreement with a freelancer", "Management of portfolio",
            "Proving skills and determining their level through tests conducted on the website",
            "Deliver the final service to the customer", "Email and Account verification"]
    },
    {
        title: "Project 12",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet. Additionally, the project offers a method for enhancing the skills and expertise of users interested in learning, along with ensuring the seamless provision of software services.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: ["/images/Ask Freelancer/1.png", "/images/Ask Freelancer/2.png",
            "/images/Ask Freelancer/3.png", "/images/Ask Freelancer/4.png",
            "/images/Ask Freelancer/5.png", "/images/Ask Freelancer/6.png",
            "/images/Ask Freelancer/7.png", "/images/Ask Freelancer/8.png",
            "/images/Ask Freelancer/9.png", "/images/Ask Freelancer/10.png",
            "/images/Ask Freelancer/11.png", "/images/Ask Freelancer/12.png",
            "/images/Ask Freelancer/13.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",
            "Bootstrap (CSS framework)",
            "Firebase",
            "Sass",
            "Pusher realtime APIs",
            "Axios (Restful API)"],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",
            "Make a complaint", "Recharge your bank wallet", "Managing publications (requesting services)",
            "Approval and agreement with a freelancer", "Management of portfolio",
            "Proving skills and determining their level through tests conducted on the website",
            "Deliver the final service to the customer", "Email and Account verification"]
    },
    {
        title: "Project 5",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet. Additionally, the project offers a method for enhancing the skills and expertise of users interested in learning, along with ensuring the seamless provision of software services.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: ["/images/Ask Freelancer/1.png", "/images/Ask Freelancer/2.png",
            "/images/Ask Freelancer/3.png", "/images/Ask Freelancer/4.png",
            "/images/Ask Freelancer/5.png", "/images/Ask Freelancer/6.png",
            "/images/Ask Freelancer/7.png", "/images/Ask Freelancer/8.png",
            "/images/Ask Freelancer/9.png", "/images/Ask Freelancer/10.png",
            "/images/Ask Freelancer/11.png", "/images/Ask Freelancer/12.png",
            "/images/Ask Freelancer/13.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",
            "Bootstrap (CSS framework)",
            "Firebase",
            "Sass",
            "Pusher realtime APIs",
            "Axios (Restful API)"],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",
            "Make a complaint", "Recharge your bank wallet", "Managing publications (requesting services)",
            "Approval and agreement with a freelancer", "Management of portfolio",
            "Proving skills and determining their level through tests conducted on the website",
            "Deliver the final service to the customer", "Email and Account verification"]
    },
    {
        title: "Ask Freelancer",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet. Additionally, the project offers a method for enhancing the skills and expertise of users interested in learning, along with ensuring the seamless provision of software services.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: [
            "/images/Ask Freelancer/1.png",
            "/images/Ask Freelancer/2.png",
            "/images/Ask Freelancer/3.png",
            "/images/Ask Freelancer/4.png",
            "/images/Ask Freelancer/5.png",
            "/images/Ask Freelancer/6.png",
            "/images/Ask Freelancer/7.png",
            "/images/Ask Freelancer/8.png",
            "/images/Ask Freelancer/9.png",
            "/images/Ask Freelancer/10.png",
            "/images/Ask Freelancer/11.png",
            "/images/Ask Freelancer/12.png",
            "/images/Ask Freelancer/13.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",
            "Bootstrap (CSS framework)",
            "Firebase",
            "Sass",
            "Pusher realtime APIs",
            "Axios (Restful API)"],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",
            "Make a complaint", "Recharge your bank wallet", "Managing publications (requesting services)",
            "Approval and agreement with a freelancer", "Management of portfolio",
            "Proving skills and determining their level through tests conducted on the website",
            "Deliver the final service to the customer", "Email and Account verification"]
    },
    {
        title: "Ehab",
        summary: "Freelance services web application",
        cover: "/images/covers/AskFreelancer.jpg",
        desc: "The project essentially emulates a methodology for executing tasks and providing on-demand technical and software services via the internet. Additionally, the project offers a method for enhancing the skills and expertise of users interested in learning, along with ensuring the seamless provision of software services.",
        demo: "/images/Ask Freelancer/VideoEditor_20220817_095747.mp4",
        gallery: [
            "/images/Ask Freelancer/1.png",
            "/images/Ask Freelancer/2.png",
            "/images/Ask Freelancer/3.png",
            "/images/Ask Freelancer/4.png",
            "/images/Ask Freelancer/5.png",
            "/images/Ask Freelancer/6.png",
            "/images/Ask Freelancer/7.png",
            "/images/Ask Freelancer/8.png",
            "/images/Ask Freelancer/9.png",
            "/images/Ask Freelancer/10.png",
            "/images/Ask Freelancer/11.png",
            "/images/Ask Freelancer/12.png",
            "/images/Ask Freelancer/13.png",
        ],
        technologies: ["React JS",
            "Prime React UI library",
            "Bootstrap (CSS framework)",
            "Firebase",
            "Sass",
            "Pusher realtime APIs",
            "Axios (Restful API)"],
        requirements: ["Chatting", "Personal account management", "Search for a service or project",
            "Make a complaint", "Recharge your bank wallet", "Managing publications (requesting services)",
            "Approval and agreement with a freelancer", "Management of portfolio",
            "Proving skills and determining their level through tests conducted on the website",
            "Deliver the final service to the customer", "Email and Account verification"]
    },
]